### ISSUE TITLE
Add support for addressing interface

### ISSUE THREAD

**Issue by WMP** [puhitaku/tftp-now#1]
Could you add support for adressing interface? For exmaple:
```
tftp-now serve -interface eth0 -ip 192.168.0.66/24 
```

**Comment by puhitaku** [comment]
[`-host` option](https://github.com/puhitaku/tftp-now#download--run) with the interface's IP address should work for you. Please try it first, and re-open here if you still have an issue.

**Comment by WMP** [comment]
Yes, I know this option. I was referring to the new option that can address the network interface. When configuring routers, the network interface goes up and down, this sometimes causes NetworkManager to address DHCP or another static IP address. I have to manually address the interface using : `` ip link set enx34298f71eee5 up ; ip a add 192.168.0.66/24 dev enx34298f71eee5; ``. It would be nice if your tool could do this for me.

**Comment by puhitaku** [comment]
That's beyond the range that a TFTP server to cover IMHO. I know what you want, and here's a generic and simple technique that will work on any setup:
 1. Prepare a switching hub. A router without DHCP will also work.
 2. Connect your PC -> the switching hub -> the router you want to setup. This will keep your interface's link up.
 3. Try transferring the firmware.

**Comment by puhitaku** [comment]
I'd like to share another reason why the technique I suggested is more effective than the feature you asked for. When the PC and router are directly connected, power cycling can cause the link to go up and down. This means that tftp-now would have to constantly monitor the interface state and set the IP address every time it detects an event, which isn't a seamless process. Additionally, since this operation isn't atomic, it can lead to complex error handling.
